Exception on /storeSurvey [GET]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\USF\Courses\ISM6930-DSP\Projects\ResumeBot\main.py", line 390, in storeSurvey
    resumeBot.dbInsertSurvey(sessionId,userMessage,botResponse,rating)
TypeError: dbInsertSurvey() takes 4 positional arguments but 5 were given
Exception on /storeSurvey [GET]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\USF\Courses\ISM6930-DSP\Projects\ResumeBot\main.py", line 390, in storeSurvey
    resumeBot.dbInsertSurvey(sessionId,userMessage,botResponse,rating)
TypeError: dbInsertSurvey() takes 4 positional arguments but 5 were given
Exception on /storeSurvey [GET]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\USF\Courses\ISM6930-DSP\Projects\ResumeBot\main.py", line 390, in storeSurvey
    resumeBot.dbInsertSurvey(sessionId,userMessage,botResponse,rating)
TypeError: dbInsertSurvey() takes 4 positional arguments but 5 were given
Exception on /storeSurvey [GET]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\USF\Courses\ISM6930-DSP\Projects\ResumeBot\main.py", line 390, in storeSurvey
    resumeBot.dbInsertSurvey(sessionId,userMessage,botResponse,rating)
  File "E:\USF\Courses\ISM6930-DSP\Projects\ResumeBot\main.py", line 307, in dbInsertSurvey
    c.execute('''INSERT INTO survey VALUES (?,?,?,?,?)''',insertValues)
sqlite3.IntegrityError: UNIQUE constraint failed: survey.sessionId
Exception on /storeSurvey [GET]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\USF\Courses\ISM6930-DSP\Projects\ResumeBot\main.py", line 390, in storeSurvey
    resumeBot.dbInsertSurvey(sessionId,userMessage,botResponse,rating)
  File "E:\USF\Courses\ISM6930-DSP\Projects\ResumeBot\main.py", line 307, in dbInsertSurvey
    c.execute('''INSERT INTO survey VALUES (?,?,?,?,?)''',insertValues)
sqlite3.OperationalError: database is locked
Exception on /storeSurvey [GET]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\USF\Courses\ISM6930-DSP\Projects\ResumeBot\main.py", line 390, in storeSurvey
    resumeBot.dbInsertSurvey(sessionId,userMessage,botResponse,rating)
  File "E:\USF\Courses\ISM6930-DSP\Projects\ResumeBot\main.py", line 307, in dbInsertSurvey
    c.execute('''INSERT INTO survey VALUES (?,?,?,?,?)''',insertValues)
sqlite3.IntegrityError: UNIQUE constraint failed: survey.sessionId
Exception on /storeSurvey [GET]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\USF\Courses\ISM6930-DSP\Projects\ResumeBot\main.py", line 390, in storeSurvey
    resumeBot.dbInsertSurvey(sessionId,userMessage,botResponse,rating)
  File "E:\USF\Courses\ISM6930-DSP\Projects\ResumeBot\main.py", line 307, in dbInsertSurvey
    c.execute('''INSERT INTO survey VALUES (?,?,?,?,?)''',insertValues)
sqlite3.OperationalError: database is locked
Exception on /storeSurvey [GET]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\USF\Courses\ISM6930-DSP\Projects\ResumeBot\main.py", line 390, in storeSurvey
    resumeBot.dbInsertSurvey(sessionId,userMessage,botResponse,rating)
  File "E:\USF\Courses\ISM6930-DSP\Projects\ResumeBot\main.py", line 307, in dbInsertSurvey
    c.execute('''INSERT INTO survey VALUES (?,?,?,?,?)''',insertValues)
sqlite3.OperationalError: database is locked
